### ISSUE TITLE
Missing source code

### ISSUE THREAD

**Issue by maechler** [cansik/yolo-hand-detection#1]
Unfortunately there is only a README file but no source code.  Is the source code somehow encoded in the README?
Excuse my stupid question, I am new to YOLO and hand tracking.

**Comment by cansik** [comment]
This has already been asked, and answered here: [Missing source code](https://github.com/cansik/yolo-handtracking/issues/1)

**Comment by maechler** [comment]
Perfect, thanks @cansik. I will check it out.
