### ISSUE TITLE
How to retrain the model ? 

### ISSUE THREAD

**Issue by AlvaroCavalcante** [cansik/yolo-hand-detection#12]
Congrats on your work, I've tested and it had a nice performance in my dataset. On the other hand, to get better results I need to fine-tune this pre-trained model with my own dataset, but I noticed that there isn't a training algorithm. So, my question is: there is a way to retrain this model to fine-tune my model?

**Comment by cansik** [comment]
Yes, it has been trained with the darkent framework, you would have to install & compile it and then run your own training. Everything is described here: https://github.com/AlexeyAB/darknet

**Comment by AlvaroCavalcante** [comment]
Thank you!
