### ISSUE TITLE
How can I get every detected hand coordinate

### ISSUE THREAD

**Issue by sevaraMS** [cansik/yolo-hand-detection#14]
Hello, how can I get coordinates of every detected hand x and y coordinates. In your code for every hand given only one x and y.
I want to get hand1: x1, y1; hand2: x2, y2. How can I get this??

**Comment by cansik** [comment]
The result of the prediction are the following values:

```python
width, height, inference_time, results = yolo.inference(mat)
```

- `width` = Width of the input image
- `height` = Height of the input image
- `inference_time` = How long it took to predict
- `results` = Here are **all detection's** stored

The results is a list of tuples, containing the following fields:

```python
# read the first detection
id, name, confidence, x, y, w, h = results[0]
```

- `id` = Id of the detected class
- `name` = Name of the detected class
- `confidence` = How confident the network is about the prediction
- `x` = X-coordinate of the bounding box (top-left)
- `y` = Y-coordinate of the bounding box (top-left)
- `w` = Width of the bounding box
- `h` = Height of the bounding box

So just iterate of the results and read your x's and y's per detection.

**Comment by sevaraMS** [comment]
thank you
