### ISSUE TITLE
How to use the CMU Hand DB?

### ISSUE THREAD

**Issue by xiaochengsky** [cansik/yolo-hand-detection#19]
Hi, Thank for sharing and it's a pretty great projects!

But I hava a question about how to use the CMU hand [Datasets?](http://domedb.perception.cs.cmu.edu/handdb.html)? Because I didn't find the bbox label about hand and it only seems to be related to the key points of the hand.

THX.

**Comment by priyankinfinnov** [comment]
@xiaochengsky did you get it to work?

**Comment by cansik** [comment]
Creating an axis-aligned bounding box out of the landmark positions is a s simple as just taking the min(xy) and max(xy) of the landmarks.
