### ISSUE TITLE
Failed to parse NetParameter file

### ISSUE THREAD

**Issue by sherineza** [cansik/yolo-hand-detection#6]
When running the code on PyCharm using command: python demo_webcam.py, I receive this error:

cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-q0nmoxxv\opencv\modules\dnn\src\darknet\darknet_importer.cpp:207: error: (-212:Parsing error) Failed to parse NetParameter file: models/cross-hands.cfg in function 'cv::dnn::dnn4_v20200609::
readNetFromDarknet'

Any way to resolve it?

**Comment by cansik** [comment]
Did you download the models?

**Comment by sherineza** [comment]
at first I hadn't. When I did it worked when running the code from pycharm. However, when I try to call it from matlab, it still gives the same error.

**Comment by cansik** [comment]
The opencv dnn module sometimes requires the net models to be reference as an absolute path. Maybe you just hand in the relative one.

**Comment by djthegr8** [comment]
I got the same error :cry:

**Comment by djthegr8** [comment]
Could this be the python version? Is it compatible with 3.8?

**Comment by djthegr8** [comment]
Wait forgot to download...
