### ISSUE TITLE
Conversion To TensorFlow or Keras

### ISSUE THREAD

**Issue by djthegr8** [cansik/yolo-hand-detection#8]
Hey,
So I wanted to do hand detection (on the browser, using TFjS), but for the conversion to a tfjs model, I would require a TensorFlow or Keras model. Could you guide me in converting these models to TF?

**Comment by djthegr8** [comment]
I am looking at [Darkflow](https://github.com/thtrieu/darkflow) would that work?

**Comment by cansik** [comment]
I would try [DW2TF](https://github.com/jinyu121/DW2TF) but never did it, so I can not help you.

**Comment by djthegr8** [comment]
DW2TF isn't working, sadly
